### PR TITLE
Py310

### PR DESCRIPTION
**Pull request by xiezhen**
update for python 310, no more python2 compatible

### CODE REVIEW

**Comment by clelange** [comment]
Awesome, thanks!

**Comment by clelange** [comment]
Could you please also release version 3.8.1 on PyPI?

**Comment by xiezhen** [comment]
I uploaded it to PyPI. I won't announce it until I fix the documentation etc. But you can use it.

**Comment by clelange** [comment]
Thank you!

Did you also happen to fix the issues with the `frontier` dialect (and if so, where can I find it)? Do you take it from http://frontier.cern.ch/dist/ ?

I currently get the following warning:

```
> brilcalc lumi -c web -r 284077
/home/bril/.local/lib/python3.10/site-packages/brilws/api.py:930: SAWarning: Dialect oracle:frontier will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  row = connection.execute(text(q),binddict).fetchone()
```

**Comment by xiezhen** [comment]
my fix of frontier dialect is not in the client code. The client code contains only change to match python310.

**Comment by clelange** [comment]
Do you think it's OK to set `supports_statement_cache = False` for now to get rid of the warning?

**Comment by xiezhen** [comment]
did you use a too much advanced version of sqlalchemy ? I tested with sqlalchemy 1.3.24, everything is fine. Could you try this version? I don't want to go too advanced with sqlalchemy version

**Comment by clelange** [comment]
Thanks for the list. Yes, I'm using SQLAlchemy 1.4.49 (requiring SQLAlchemy<2) -- I guess I'll also just downgrade to 1.3.x.

**Comment by xiezhen** [comment]
well, you can tell me where to put statement supports_statement_cache = False, so that I can use it for the future upgrade of sqlalchemy in brilconda.

**Comment by clelange** [comment]
OK, I'll try to figure this out, but probably won't manage today anymore. Thanks for your help!

**Comment by clelange** [comment]
Here's the fix: https://gitlab.cern.ch/cms-cloud/brilws-docker/-/commit/698a3166d7b75c429fadb232c9576199b06b0c0b

**Pull request merged**
